#####
## FreeIPA specific configuration
#####

from netboxcommunity/netbox:latest-ldap as ldap-ipa

RUN apk add --no-cache \
      libc-dev \
      krb5-dev \
      krb5 \
      gcc

RUN pip install --no-warn-script-location \
      python-freeipa \
      requests_kerberos \
      requests_gssapi
